name: OpenAiCodeReview

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Create libs directory
        run: mkdir -p ./libs
      - name: Download openai-code-review-sdk JAR
        run: wget -O ./libs/ai-code-review-sdk.jar https://github.com/liuliuliukaikaikai/code-review-log/releases/download/v1/ai-code-review-sdk.jar
      - name: Run Code Review
        run: java -jar ./libs/ai-code-review-sdk.jar
